const DEFAULT_DATE_FORMAT = 'DD-MM-YYYY'
const TIME_FORMAT = 'HH:mm'
const SERVER_POINT = 'http://127.0.0.1:3001'
const RESERVATIONS_ENDPOINT = `api/reservations`
const DAY_IN_MINUTES = 1440
const PAGE_TITLE = 'Confr'
const CALENDAR_HEADER_HEIGHT = 70
const CAL_FIRST_COLUMN_WIDTH = 80

export {
  DEFAULT_DATE_FORMAT,
  TIME_FORMAT,
  SERVER_POINT,
  RESERVATIONS_ENDPOINT,
  DAY_IN_MINUTES,
  PAGE_TITLE,
  CALENDAR_HEADER_HEIGHT,
  CAL_FIRST_COLUMN_WIDTH,
}
